services:
  - type: web
    name: django-portfolio
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_project.settings_production
    healthCheckPath: /