services:
  - type: web
    name: django-portfolio
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_project.settings_render
      - key: ALLOWED_HOSTS
        value: future-fs-01-a6ek.onrender.com,.onrender.com,localhost,127.0.0.1
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DB_HOST
        value: ""
      - key: DB_NAME
        value: ""
      - key: DB_USER
        value: ""
      - key: DB_PASSWORD
        value: ""
      - key: DB_PORT
        value: ""
    healthCheckPath: /health/
    autoDeploy: false
    # Add disk for media files
    disk:
      name: media
      mountPath: /app/media
      sizeGB: 1