services:
  - type: web
    name: django-portfolio
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_project.settings_production
    healthCheckPath: /
    pythonVersion: "3.10"